### ISSUE TITLE
Basic ethereum interaction 

### ISSUE THREAD

**Issue by artall64** [BANKEX/plasma-research#40]
In `hardcode` branch we've started work on infrastructure for plasma prime. We need to add:
1) Add ethereum account private key as a parameter of the app
2) Add gourutine that will periodically request ethereum balance and store it in the internal variable
3) Add Http handler for the client that will return current Ethereum connection status - Should return be set to false and return error description if last get balance request was failed

**Comment by EnoRage** [comment]
1. Done
2. Alex is doing that
